### ISSUE TITLE
Cannot load .es6 file extension

### ISSUE THREAD

**Issue by protoEvangelion** [arackaf/simple-react-bootstrap#1]
I copied the example for the Navbar exactly and it throws this error: 
```
\simple-react-bootstrap\src\buttonDropdown.es6 Unexpected token (5:7)
You may need an appropriate loader to handle this file type.
```
It gives me that error for:  `modal.es6` and `navBar.es6` as well.

I tried adding .es6 file extension in my webpack file but that does not help.

**Comment by arackaf** [comment]
Yeah, sorry about that.  I ran into the same issue when I moved my project (which uses this utility) to webpack.  

Until I can properly fix that, here's the webpack config I'm using with it, which should work (you probably won't need the exact same presets and plugins - try with what you're otherwise using).

There's also a CJS and UMD build that npm should be installing - you could also use those, along with an alias in webpack.

```
{
    test: /\.es6$/,
    include: /simple-react-bootstrap/,
    loader: 'babel-loader',
    query: {
        presets: ['react', 'es2015-webpack', 'stage-1', 'stage-2'],
        plugins: ['transform-decorators-legacy', 'external-helpers']
    }
}
```

**Comment by arackaf** [comment]
@protoEvangelion grab the latest off npm and let me know if that solves things?

It's not quite perfect - tree shaking won't happen yet with Webpack, but I plan to fix that.  Bit it should *work* without error.

**Comment by protoEvangelion** [comment]
@arackaf   Thanks for the response :) I tried a similar config in Webpack 2 but it is a bit different because they changed their API.  Out of curiosity, what is the reason that the file extension is `.es6`?

**Comment by arackaf** [comment]
Was a way for me to easily differentiate es6 files versus their transpiled results - I only recently got onto babel and my old stuff, like this, used manual gulp/babel processes to do transpilation.

**Comment by arackaf** [comment]
Let me know if you have any other problems.
